### ISSUE TITLE
软件运行时报错

### ISSUE THREAD

**Issue by kateflyup** [chenym1/genetribe#1]
您好，我用您的genetribe工具运行自己的数据时，出现了如图错误：
![image](https://user-images.githubusercontent.com/28924937/116262481-27911d80-a7ab-11eb-8071-c4d796a11031.png)
之后，我又尝试安装与说明完全相同的版本bedtools、blast、MCscan，使用了测试数据，仍然报相同错误，请问您知道是什么原因吗？
期待得到您的回复，谢谢！

**Comment by chenym1** [comment]
I think it is a problem with the python matplotlib package version. You can try to create a new conda environment and install all dependent packages.
