### ISSUE TITLE
Error when using pre-computed blast result

### ISSUE THREAD

**Issue by Zhuxitong** [chenym1/genetribe#2]
Hi @chenym1 

I want to skip the blast process as it takes much time. So I used diamond to align protein fa file first using the following command for all four possible specie combination:

> diamond makedb --in Obrac.fa -d Obrac &> Obrac_db.log
diamond makedb --in Omh63.fa -d Omh63 &> Omh63_db.log
diamond blastp -e 1e-5 -p 2 -q ${querie}.fa -d ${target}.dmnd -o ${target}_${querie}.blast -f 6 -k 5

The -f para specific the output format in blast tab. I checked this file and it's same with the file jcvi needs. The using the following command, I run genetribe:

> genetribe core -l Obrac -f Omh63 -d ./ -r -s + -n 1

The -s is specificed to '+' as I already selected the longest transcript for each gene so I want to use this rare symbo to skip the selection process in your pipeline. 

However, I got the following problems:

> [11:51:31] DEBUG    Assuming --qbed=Obrac.bed --sbed=Omh63.bed                                                                      synteny.py:500
           DEBUG    Load file `Obrac.bed`                                                                                               base.py:37
[11:51:32] DEBUG    Load file `Omh63.bed`                                                                                               base.py:37
           DEBUG    Load BLAST file `Obrac.Omh63.last` (total 86573 lines)                                                       blastfilter.py:48
           DEBUG    Load file `Obrac.Omh63.last`                                                                                        base.py:37
[11:51:33] WARNING  OsMH_10T0277800-mRNA-2 not in Obrac.bed                                                                      blastfilter.py:67
           WARNING  OsMH_09T0060300.1 not in Obrac.bed                                                                           blastfilter.py:67
           WARNING  OsMH_04T0543900-mRNA-2 not in Obrac.bed                                                                      blastfilter.py:67
           WARNING  OsMH_02T0267100-mRNA-2 not in Obrac.bed                                                                      blastfilter.py:67
           WARNING  OsMH_10T0367800-mRNA-1 not in Obrac.bed                                                                      blastfilter.py:67

It's so strange that jcvi would look for a MH63 gene in the bed of Obrac. 

Is there anything I have overlooked?  I think this should make sense.

**Comment by chenym1** [comment]
Hi, xitong,
In 'diamond blastp -e 1e-5 -p 2 -q ${querie}.fa -d ${target}.dmnd -o ${target}_${querie}.blast -f 6 -k 5', you should replace '${target}_${querie}.blast' with '${querie}_${target}.blast'

**Comment by Zhuxitong** [comment]
Thanks I should realize this problem. I will try it!


------------------ Original ------------------
From: Yongming Chen ***@***.***&gt;
Date: Fri,Jun 18,2021 0:32 PM
To: chenym1/genetribe ***@***.***&gt;
Cc: Zhu xitong ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [chenym1/genetribe] Error when using pre-computed blast result (#2)





 
Hi, xitong,
 In 'diamond blastp -e 1e-5 -p 2 -q ${querie}.fa -d ${target}.dmnd -o ${target}${querie}.blast -f 6 -k 5', you should replace '${target}${querie}.blast' with '${querie}_${target}.blast'

**Comment by Zhuxitong** [comment]
Hi @chenym1 

Yes indeed I set wrong output prefix in diamond and your suggestion is right. 

I have some other questions and maybe those should be in a new ISSUE but I shall just ask here.

1. For the .chrlist file, I guess only the last character e.g. A in chrNA or nothing after N e.g. the one in Oryza_sativa_Japonica.chrlist is important for penalty. So is this mean that every abbr. in chrlist (like chrNA chrNB and chrND in another file) is a chromosome group ? For example if a pair of genes are in A and B, respectively, they would be penalized even A and B are in same chrlist file? 
> cat Oryza_sativa_Japonica.chrlist
N
2. At last, we could get 7 files for a comparison (1 RBH, 2 SBH, 2 Singleton, 2 1toMany). Will you have any suggestions on how to integrate many comparison like I think if we have three species, we can use the files of A->B, and B->C.
3. Moreover, I really like the this picture in you paper. Could you please kindly provide me ideas to draw such pictures.
![QQ图片20210618154709](https://user-images.githubusercontent.com/23165349/122526064-78efb780-d04c-11eb-9bfe-6b66f63711ff.png)

Any little help is very appreciated.

**Comment by chenym1** [comment]
Hi, @Zhuxitong 
Sorry to reply you now, 
1. A pair of genes would be penalized even A and B are in same chrlist file, for example, gene1 in chr1A, while gene2 in chr2B.
2. The effect of using RBH will be better.
3. The figure is plotted using R graphics package. The homologous relationships are generated using GeneTribe.
hope this helps.

**Comment by Zhuxitong** [comment]
@chenym1  Many thanks. I will close this issues.
