### ISSUE TITLE
If the genome assembly level is only contig level, what should the .chrlist file look like?

### ISSUE THREAD

**Issue by Starry-Sky-hu** [chenym1/genetribe#3]
Thanks so much for this very valuable resource! 

I have several genomes, and these is only contig level, what should the .chrlist file look like?

**Comment by chenym1** [comment]
If the contig is names as contig10100 in your genome assembly, manbe you can use "contigN".

**Comment by chenym1** [comment]
If the contig is named as 'contig10100' in your genome assembly, you can use 'contigN'.

**Comment by Starry-Sky-hu** [comment]
> If the contig is named as 'contig10100' in your genome assembly, you can use 'contigN'.

Thanks a lot!

These genomes have their own contig(or chromosome) name, and I use the same .chrlist file in genomes with different contig(or chromosome) names. There have no error, and results look like right. Is there any problem with this?
