### ISSUE TITLE
how to visualize?

### ISSUE THREAD

**Issue by Starry-Sky-hu** [chenym1/genetribe#4]
The excellent usefulness of the software! But I don't know how to visualize the results.

Plot like this results:
![image](https://user-images.githubusercontent.com/53527045/149950250-eb956d9d-0c87-49f7-8dca-5e6c0643c8b2.png)

**Comment by chenym1** [comment]
genetribe temporarily does not provide visualization functions, you can try some visualization tools, such as RIdeogram and MCscan.
